name: publish-docs-to-github-pages
on:
  pull_request:
    branches:
      - main
    types:
      - closed
    paths:
      - "src/docs/package.json"
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: use pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ">=8.5.0 <9.0.0"
      - name: use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ">=18.0.0 <19.0.0"
          cache: "pnpm"
      - name: install dependencies
        run: pnpm i
      - name: build packages
        run: pnpm build --filter docs
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
