name: publish-docs-to-github-pages
on:
  pull_request:
    branches:
      - main
    types:
      - closed
    paths:
      - "src/docs/package.json"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: use pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ">=8.5.0 <9.0.0"
      - name: use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ">=18.0.0 <19.0.0"
          cache: "pnpm"
      - name: install dependencies
        run: pnpm i
      - name: build packages
        run: pnpm build --filter docs
      - name: create .nojekyll file
        run: touch dist/.nojekyll
      - name: deploy
        uses: JamesIves/github-pages-deploy-action@4.4.0
        with:
          branch: gh-pages
          folder: dist
